name: lgoby_month_picker
description: Flutter widget for month year picker built based on Flutter's date picker design.
version: 0.1.0+1
homepage: https://github.com/lgoby/flutter-month-picker

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: '>=3.10.6'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
